# This GitHub Actions workflow is designed to execute Cypress tests using Chrome on various events 
# such as manual trigger, push to the master branch, or pull requests to the master branch.

name: 01_Tests Execution - Pre-defined browser Chrome

on:
  # Manual Trigger with pre-defined browser Chrome
  workflow_dispatch:

  # Trigger on push to the main branch
  push:
    branches:
      - main

  # Trigger on pull request to the main branch
  pull_request:
    branches:
      - main

jobs:
  cypress:
    # Define the machine on which tests will execute
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checking out the code from the GitHub repository to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Installing Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      # Step 3: Installing dependencies required for Cypress
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Cypress tests on Chrome browser
      - name: Run Cypress tests
        run: npm run cy:tests:CHROME

      # Step 5: Upload test reports as artifacts
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: cypress/reports